language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.2
  - 7.3

matrix:
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
    - composer selfupdate || true
    - composer update $COMPOSER_FLAGS

script:
    - echo '[phpspec] Running specification tests'; ./vendor/bin/phpspec run
    - echo '[phpunit] Running example tests'; ./vendor/bin/phpunit
    - echo '[phpunit] Running CS tests'; ./vendor/bin/php-cs-fixer fix --dry-run
